server:
  port: 20001
# 配置数据源
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/changedata?serverTimezone=UTC
    username: root
    password: 123456

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# 注意：一定要对应mapper映射xml文件的所在路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.example.changedata.model


#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql